# basic information
# will be used to generate SEO and web content
title: Jia's Lab
email: jiaslab@outlook.com
phone: 0571-2354758834
description: "Dr. Huijue Jia's personal website"
github_username:  jiaslab

# Build settings
# custom defined collections
collections:
  - publications
  - staff
  - news

# sass partials location
sass:
    sass_dir: _sass

# define mobile
on_mobile: 600px

# plugins
plugins:
  - jekyll-seo-tag        # is used to generated seo tag